-- MySQL Script generated by MySQL Workbench
-- mar 31 oct 2017 14:45:50 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DeducionesEmpleadoBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DeducionesEmpleadoBD` ;

-- -----------------------------------------------------
-- Schema DeducionesEmpleadoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DeducionesEmpleadoBD` DEFAULT CHARACTER SET utf8 ;
USE `DeducionesEmpleadoBD` ;

-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nombre_cargo` VARCHAR(70) NOT NULL,
  `Sueldo_idPlanilla` INT NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `TipoContrato` VARCHAR(45) NULL,
  `horaEntrada` INT NULL,
  `horaSalida` INT NULL,
  `diasDeTrabajo` INT NULL,
  `fechaContratacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idContrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `p_nombre` VARCHAR(50) NOT NULL,
  `s_nombre` VARCHAR(50) NULL,
  `p_apellido` VARCHAR(50) NOT NULL,
  `s_apellido` VARCHAR(50) NULL,
  `identidad` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `edad` INT NOT NULL,
  `fecha_nacimineto` DATE NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `cod_empleado` VARCHAR(45) NULL,
  `Cargo_idCargo` INT NOT NULL,
  `IdEncargado` INT NOT NULL,
  `idContrato` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Cargo_idCargo`, `idContrato`),
  INDEX `fk_Empleado_Cargo1_idx` (`Cargo_idCargo` ASC),
  INDEX `fk_Empleado_Empleado1_idx` (`IdEncargado` ASC),
  INDEX `fk_Empleado_Sueldos1_idx` (`idContrato` ASC),
  CONSTRAINT `fk_Empleado_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `DeducionesEmpleadoBD`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Empleado1`
    FOREIGN KEY (`IdEncargado`)
    REFERENCES `DeducionesEmpleadoBD`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Sueldos1`
    FOREIGN KEY (`idContrato`)
    REFERENCES `DeducionesEmpleadoBD`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Tipo_Permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Tipo_Permiso` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Tipo_Permiso` (
  `idTipo_Permiso` INT NOT NULL,
  `nombre_permiso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Permisos` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `descrip_permiso` VARCHAR(70) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `num_dias` INT NOT NULL,
  `Tipo_Permiso_idTipo_Permiso` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `idResposable` INT NOT NULL,
  `estadoPermiso` INT NULL,
  PRIMARY KEY (`idPermisos`, `idEmpleado`, `idResposable`),
  INDEX `fk_Permisos_Tipo_Permiso1_idx` (`Tipo_Permiso_idTipo_Permiso` ASC),
  INDEX `fk_Permisos_Empleado1_idx` (`idEmpleado` ASC),
  INDEX `fk_Permisos_Empleado2_idx` (`idResposable` ASC),
  CONSTRAINT `fk_Permisos_Tipo_Permiso1`
    FOREIGN KEY (`Tipo_Permiso_idTipo_Permiso`)
    REFERENCES `DeducionesEmpleadoBD`.`Tipo_Permiso` (`idTipo_Permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `DeducionesEmpleadoBD`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Empleado2`
    FOREIGN KEY (`idResposable`)
    REFERENCES `DeducionesEmpleadoBD`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Deducciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Deducciones` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Deducciones` (
  `idDeducciones` INT NOT NULL,
  `dedu_IHSS` FLOAT NOT NULL,
  `dedu_RAP` FLOAT NOT NULL,
  `dedu_aportaciones` FLOAT NOT NULL,
  `dedu_falta` FLOAT NULL,
  `Tipo_Deducciones_idTipo_Deduccion` INT NOT NULL,
  `Permisos_idPermisos` INT NOT NULL,
  PRIMARY KEY (`idDeducciones`, `Permisos_idPermisos`),
  INDEX `fk_Deducciones_Permisos1_idx` (`Permisos_idPermisos` ASC),
  CONSTRAINT `fk_Deducciones_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `DeducionesEmpleadoBD`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Asistencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Asistencias` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Asistencias` (
  `idAsistencias` INT NOT NULL,
  `fecha` DATE NULL,
  `hora_entrada` DATETIME NULL,
  `hora_salida` DATETIME NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Empleado_Cargo_idCargo` INT NOT NULL,
  `EstadoAsistencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idAsistencias`, `Empleado_idEmpleado`, `Empleado_Cargo_idCargo`),
  INDEX `fk_Asistencias_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Cargo_idCargo` ASC),
  CONSTRAINT `fk_Asistencias_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Cargo_idCargo`)
    REFERENCES `DeducionesEmpleadoBD`.`Empleado` (`idEmpleado` , `Cargo_idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeducionesEmpleadoBD`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeducionesEmpleadoBD`.`Pago` ;

CREATE TABLE IF NOT EXISTS `DeducionesEmpleadoBD`.`Pago` (
  `idPago` INT NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `total_deducciones` FLOAT NOT NULL,
  `total_pago` FLOAT NOT NULL,
  `IdDeducciones` INT NOT NULL,
  `IdPermisos` INT NOT NULL,
  `IdEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPago`, `IdDeducciones`, `IdPermisos`, `IdEmpleado`),
  INDEX `fk_Pago_Deducciones1_idx` (`IdDeducciones` ASC, `IdPermisos` ASC),
  INDEX `fk_Pago_Empleado1_idx` (`IdEmpleado` ASC),
  CONSTRAINT `fk_Pago_Deducciones1`
    FOREIGN KEY (`IdDeducciones` , `IdPermisos`)
    REFERENCES `DeducionesEmpleadoBD`.`Deducciones` (`idDeducciones` , `Permisos_idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Empleado1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `DeducionesEmpleadoBD`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
